# Generated by Django 3.2.6 on 2021-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_unique_numbers',
            field=models.CharField(max_length=100, null=True, verbose_name='결제 고유번호'),
        ),
    ]
