# Generated by Django 3.2.6 on 2021-08-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_payment_unique_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default=False, max_length=10, verbose_name='결제 완료 여부'),
        ),
    ]
